In [1]:
import pandas as pd

In [2]:
file_path= "../data/Universe ESG.xlsx"
df_return = pd.read_excel(file_path, sheet_name= "Universe")
df_info = pd.read_excel(file_path, sheet_name= "Sheet2")

In [3]:
# traitement du return
df_return2= df_return.iloc[1:, 3:].transpose()#.set_index(1)
df_return2.columns= df_return2.iloc[0, :]
df_return3= df_return2.iloc[2:, :]
df_return3["Date1"]= df_return3.iloc[:, 0]
df_return3["Date2"]= df_return3.iloc[:, 1]

df_return3= df_return3.iloc[:, 3:]
df_return3= df_return3.reset_index(drop= True)
df_return3.head()

C:\Users\Wenceslas\Anaconda3\envs\cours\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Users\Wenceslas\Anaconda3\envs\cours\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

Unnamed: 3,HES US Equity,NEM US Equity,INTC US Equity,IFF US Equity,MOS US Equity,EXC US Equity,KMB US Equity,JNJ US Equity,BAX US Equity,F US Equity,...,IR US Equity,BKR US Equity,WEC US Equity,OXY US Equity,WMB US Equity,UNP US Equity,WM US Equity,CCL US Equity,Date1,Date2
0,-4.47934,-9.40605,-4.90196,-3.33009,-10.4135,-6.6503,-6.78073,-2.40646,-1.85753,8.4,...,-9.17739,12.2188,-1.78607,-3.70006,-1.13852,-5.32081,-5.20556,5.17513,2009-12-31 00:00:00,2010-01-31 00:00:00
1,1.74771,14.979,6.67166,5.88383,9.21661,-3.94573,2.27311,0.992332,-1.14603,8.30258,...,-1.47426,5.83039,-0.212952,1.92749,3.35893,11.8049,3.02652,8.20802,2010-01-31 00:00:00,2010-02-28 00:00:00
2,6.55208,3.5538,8.57282,13.8258,4.07604,1.17783,4.66159,3.49206,2.73219,7.06985,...,9.27609,-2.25376,2.02354,6.30226,7.76156,8.80214,5.25441,8.12013,2010-02-28 00:00:00,2010-03-31 00:00:00
3,1.59872,10.1119,2.46747,5.07657,-15.8466,-0.502169,-2.57634,-1.38037,-18.866,3.57995,...,6.05105,6.23399,6.27403,4.87343,2.20779,3.21964,0.726111,7.25309,2010-03-31 00:00:00,2010-04-30 00:00:00
4,-16.2864,-4.02996,-5.55099,-11.1599,-9.62648,-10.3449,-0.914137,-8.50183,-10.5676,-9.90783,...,0.892374,-23.1012,-5.96525,-6.93661,-16.349,-5.14649,-5.35363,-12.8828,2010-04-30 00:00:00,2010-05-31 00:00:00

In [4]:
df_return4= df_return3
df_return4= df_return4.dropna(axis= 1)
# df_return4.head()
ticker_good= [i for i in df_return4.iloc[:, 0:48].columns]
ticker_good

['HES US Equity',
 'NEM US Equity',
 'INTC US Equity',
 'IFF US Equity',
 'MOS US Equity',
 'EXC US Equity',
 'KMB US Equity',
 'JNJ US Equity',
 'BAX US Equity',
 'F US Equity',
 'COP US Equity',
 'WFC US Equity',
 'WY US Equity',
 'TGT US Equity',
 'MMM US Equity',
 'CMI US Equity',
 'HAS US Equity',
 'DUK US Equity',
 'EMN US Equity',
 'BK US Equity',
 'UFS US Equity',
 'ECL US Equity',
 'SLB US Equity',
 'UPS US Equity',
 'T US Equity',
 'NSC US Equity',
 'PPL US Equity',
 'MO US Equity',
 'JLL US Equity',
 'C US Equity',
 'ABT US Equity',
 'AMD US Equity',
 'CVX US Equity',
 'CMA US Equity',
 'DTE US Equity',
 'HSY US Equity',
 'KIM US Equity',
 'NBL US Equity',
 'IBM US Equity',
 'WELL US Equity',
 'IR US Equity',
 'BKR US Equity',
 'WEC US Equity',
 'OXY US Equity',
 'WMB US Equity',
 'UNP US Equity',
 'WM US Equity',
 'CCL US Equity']

In [5]:
df_return4.to_csv("../data/return.csv", index= False, header= True)

del df_return
del df_return2
del df_return3
del df_return4

In [8]:
# traitement des infos
info= ["EBITDA_TO_REVENUE", "EPS_GROWTH", "CURRENT_EV_TO_T12M_EBITDA", 
      "EBITDA_TO_INTEREST_EXPN", "TOT_DEBT_TO_EBITDA", "PE_RATIO", "DIVIDEND_INDICATED_YIELD",
      "EQY_DVD_YLD_IND"]

ticker_good= ticker_good + ["Date"]
df_info2= df_info.iloc[15:, 20:]
ticker= df_info2.iloc[0, :].values[1:]
ticker= ["Date"] + ticker.tolist()
print(df_info2.shape)

df_info2= df_info2.iloc[2:, :]
df_info2.columns= ticker
date= df_info2["Date"].iloc[1:]

for j in info:
    test= (df_info2.iloc[0,:] == j).values
    index_col= [i for i, x in enumerate(test) if x]
    df_test= df_info2
    df_test= df_test.iloc[:, test]
    df_test["Date"]= date
    df_test["Metric"]= df_test.iloc[0, 1]
    df_test= df_test.iloc[1:, :]
    ticker_good= [i for i in df_test.columns if i not in ["Date", "Metric"]]
    df_test= df_test[ticker_good]
    # on a des nan, on les remplace par la moyenne de la ligne
    df_test[ticker_good] = df_test[ticker_good].apply(lambda row: row.fillna(row.mean()), axis=1)
    df_test["Date"] = date
#     print(df_test.columns)
    df_test.to_csv("../data/{}.csv".format(j), index= False, header= True)

(43, 501)

C:\Users\Wenceslas\Anaconda3\envs\cours\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\Wenceslas\Anaconda3\envs\cours\lib\site-packages\ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy